[".config/zsh/zsh-autosuggestions"]
  type = "git-repo"
  url = "https://github.com/zsh-users/zsh-autosuggestions.git"
  refreshPeriod = "168h"


[".config/tmux/themes/nord-tmux"]
  type = "git-repo"
  url = "https://github.com/nordtheme/tmux.git"
  branch = "v2.1.2"
  refreshPeriod = "168h"

